docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - "Controller Plugin": controller-plugin.md
    - "View Helper": view-helper.md
site_name: zend-mvc-plugin-flashmessenger
site_description: 'Plugin for creating and exposing flash messages via zend-mvc controllers'
repo_url: 'https://github.com/zendframework/zend-mvc-plugin-flashmessenger'
extra:
    show_special_homepage: true
