docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - "Controller Plugin": flash-messenger-plugin.md
    - "View Helper": flash-messenger-view-helper.md
site_name: zend-mvc-plugin-flashmessenger
site_description: 'Plugin for creating and exposing flash messages via zend-mvc controllers'
repo_url: 'https://github.com/zendframework/zend-mvc-plugin-flashmessenger'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
