docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - View Helper: flash-messenger-view-helper.md
site_name: laminas-mvc-plugin-flashmessenger
site_description: 'laminas-mvc-plugin-flashmessenger: Flash messages for laminas-mvc controllers'
repo_url: 'https://github.com/laminas/laminas-mvc-plugin-flashmessenger'
