docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
site_name: laminas-mvc-plugin-flashmessenger
site_description: 'laminas-mvc-plugin-flashmessenger: Flash messages for laminas-mvc controllers'
repo_url: 'https://github.com/laminas/laminas-mvc-plugin-flashmessenger'
